# MariaDB
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # DB Source URL
    url: jdbc:mariadb://localhost:33006/bunena
    # DB username
    username: bunena
    # DB password
    password: bunena1234!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  # 코드 변경 후에 만들어진 결과를 보관(캐싱)하지 않도록 설정해 두는 것
  thymeleaf:
    cache: false
